[package]
name = "aoc-2023-03"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "part1"
path = "part1.rs"

[[bin]]
name = "part2"
path = "part2.rs"

[dependencies]
regex = "1.10.2"
lazy_static = "1.4.0"
